// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "providers": string;
      "activeProviderId": string;
      "model": string;
      "baseURL": string;
      "apiKey": string;
      "temperature": number;
      "concurrency": number;
      "requestTimeoutSec": number;
      "maxRetries": number;
      "batchChars": number;
      "systemPromptExtra": string;
      "sourceLang": string;
      "targetLang": string;
      "skipReferences": boolean;
      "firstPage": number;
      "lastPage": number;
      "bilingualLayout": string;
      "originalOnLeft": boolean;
      "columnGapPt": number;
      "drawDivider": boolean;
      "outputMode": string;
      "customOutputDir": string;
      "suffix": string;
      "overwrite": boolean;
      "addAsAttachment": boolean;
      "openAfterExport": boolean;
      "revealAfterExport": boolean;
      "cjkFontPath": string;
      "fallbackFontPath": string;
      "cacheEnabled": boolean;
      "debug": boolean;
    };
  }
}
